#!/usr/bin/env python3
"""
lil_agent.py — Animated desktop character for Linux (Arch / KDE Plasma / X11)

Inspired by ryanstephen/lil-agents (macOS).

A transparent, borderless, always-on-top overlay walks an animated character
across the bottom of the screen (above the panel/dock).  Clicking on the
visible (opaque) part of the character opens a greeting dialog; clicks on
transparent pixels pass through to windows underneath.

Compatibility : Arch Linux · KDE Plasma · X11
Requirements  : PyQt5, python-pillow  (run create_assets.py first)
Optional      : GStreamer + gst-python  (for .mov/.webm transparent video)

Quick start
-----------
    python create_assets.py   # generate demo walk-cycle frames
    python lil_agent.py       # launch the overlay
"""

import glob
import os
import random
import sys
from typing import Optional

from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QBitmap, QColor, QImage, QPainter, QPixmap
from PyQt5.QtWidgets import (
    QApplication,
    QDialog,
    QHBoxLayout,
    QLabel,
    QPushButton,
    QVBoxLayout,
    QWidget,
)

# ── Optional GStreamer for transparent video playback ──────────────────────────
try:
    import gi
    gi.require_version("Gst", "1.0")
    gi.require_version("GstApp", "1.0")
    from gi.repository import Gst  # noqa: F401 — used inside FrameSource
    Gst.init(None)
    _HAS_GST = True
except Exception:
    _HAS_GST = False

# ── Configuration ──────────────────────────────────────────────────────────────
_SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR   = os.path.join(_SCRIPT_DIR, "assets")

# Pixels to preserve above the bottom edge (matches a standard 48 px KDE panel).
# Adjust if your panel is taller or shorter.
PANEL_HEIGHT  = 48

# Pixels to move per walk-tick.  The walk timer fires at ~60 Hz, so
# WALK_SPEED = 4 → ~240 px/s (crosses a 1920 px screen in ~8 s).
WALK_SPEED    = 4

# Walk-cycle frame rate (FPS)
ANIMATION_FPS = 12


# ─────────────────────────────────────────────────────────────────────────────
#  FrameSource — loads animation frames from disk or generates a placeholder
# ─────────────────────────────────────────────────────────────────────────────

class FrameSource:
    """
    Provides animation frames as :class:`QPixmap` objects.

    Load priority
    ~~~~~~~~~~~~~
    1. **PNG frame sequence** — ``assets/walk_*.png``
       (generated by ``create_assets.py`` or your own RGBA PNGs)
    2. **Transparent video** — ``assets/*.webm / *.mov / *.mkv``
       decoded frame-by-frame via GStreamer  (requires ``gst-python``)
    3. **Built-in placeholder** — simple coloured rectangles so the
       overlay is always runnable even without any assets.
    """

    def __init__(self) -> None:
        self._frames: list[QPixmap] = []
        self._idx    = 0
        self.source_desc = "none"
        self._load()

    # ── public interface ───────────────────────────────────────────────────────

    @property
    def frame_count(self) -> int:
        return len(self._frames)

    def current(self) -> QPixmap:
        if not self._frames:
            return QPixmap()
        return self._frames[self._idx % len(self._frames)]

    def advance(self) -> None:
        if self._frames:
            self._idx = (self._idx + 1) % len(self._frames)

    def frame_size(self) -> tuple[int, int]:
        if self._frames:
            px = self._frames[0]
            return px.width(), px.height()
        return (80, 130)

    # ── private helpers ────────────────────────────────────────────────────────

    def _load(self) -> None:
        if self._try_png_sequence():
            return
        if _HAS_GST and self._try_gst_video():
            return
        self._make_placeholder()

    def _try_png_sequence(self) -> bool:
        files = sorted(glob.glob(os.path.join(ASSETS_DIR, "walk_*.png")))
        if not files:
            return False
        for path in files:
            px = QPixmap(path)
            if not px.isNull():
                self._frames.append(px)
        if self._frames:
            self.source_desc = f"PNG sequence ({len(self._frames)} frames)"
            return True
        return False

    def _try_gst_video(self) -> bool:
        """Extract all frames from a transparent video using GStreamer."""
        candidates: list[str] = []
        for pat in ("*.webm", "*.mov", "*.mkv", "*.mp4"):
            candidates.extend(glob.glob(os.path.join(ASSETS_DIR, pat)))
        if not candidates:
            return False
        return self._extract_gst_frames(candidates[0])

    def _extract_gst_frames(self, path: str) -> bool:
        """
        Run a GStreamer pipeline to decode *path* into BGRA frames and store
        them as QPixmap objects.  Supports VP9+alpha (.webm) and HEVC+alpha
        (.mov/.mkv) depending on installed gst-plugins-* packages.
        """
        from gi.repository import Gst as _Gst  # already initialised

        pipeline_desc = (
            f'filesrc location="{path}" ! decodebin'
            " ! videoconvert ! video/x-raw,format=BGRA"
            " ! appsink name=sink sync=false max-buffers=500"
            "   drop=false emit-signals=false"
        )
        pipeline = None
        try:
            pipeline = _Gst.parse_launch(pipeline_desc)
            appsink  = pipeline.get_by_name("sink")

            pipeline.set_state(_Gst.State.PLAYING)
            # Wait for the pipeline to reach PLAYING (up to 5 s)
            ret, _state, _ = pipeline.get_state(_Gst.SECOND * 5)
            if _state != _Gst.State.PLAYING:
                raise RuntimeError("Pipeline did not reach PLAYING state")

            w = h = 0
            frames: list[QPixmap] = []
            bus = pipeline.get_bus()

            while len(frames) < 500:
                # Poll for EOS / ERROR without blocking
                msg = bus.timed_pop_filtered(
                    _Gst.SECOND // 4,
                    _Gst.MessageType.EOS | _Gst.MessageType.ERROR,
                )
                if msg:
                    break

                sample = appsink.try_pull_sample(0)
                if sample is None:
                    continue

                if w == 0:
                    s = sample.get_caps().get_structure(0)
                    w = s.get_int("width")[1]
                    h = s.get_int("height")[1]

                buf  = sample.get_buffer()
                ok, info = buf.map(_Gst.MapFlags.READ)
                if ok:
                    # GStreamer BGRA on LE = Qt ARGB32 in memory layout
                    img = QImage(
                        bytes(info.data), w, h, w * 4, QImage.Format_ARGB32
                    )
                    frames.append(QPixmap.fromImage(img.copy()))
                    buf.unmap(info)

            pipeline.set_state(_Gst.State.NULL)

            if frames:
                self._frames = frames
                self.source_desc = (
                    f"video: {os.path.basename(path)} ({len(frames)} frames)"
                )
                return True

        except Exception as exc:
            print(f"[lil_agent] GStreamer error: {exc}")
            if pipeline is not None:
                pipeline.set_state(_Gst.State.NULL)

        return False

    def _make_placeholder(self) -> None:
        """Generate simple coloured-rectangle placeholder frames."""
        print(
            "[lil_agent] No assets found — using placeholder character.\n"
            "            Run  python create_assets.py  to generate walk frames."
        )
        W, H = 80, 130
        colours = [
            QColor(65, 105, 225, 230),
            QColor(50,  90, 210, 230),
            QColor(80, 120, 240, 230),
        ]
        for i in range(8):
            img = QImage(W, H, QImage.Format_ARGB32)
            img.fill(Qt.transparent)
            p = QPainter(img)
            p.setRenderHint(QPainter.Antialiasing)
            # Torso
            p.setBrush(colours[i % len(colours)])
            p.setPen(Qt.NoPen)
            p.drawRoundedRect(20, 35, 40, 55, 8, 8)
            # Head
            p.setBrush(QColor(255, 200, 150, 255))
            p.drawEllipse(27, 8, 26, 26)
            # Legs (simple alternating offset)
            offset = 8 if (i % 4 < 2) else -8
            p.setBrush(QColor(30, 30, 90, 255))
            p.drawRoundedRect(20,      90, 16, 34, 4, 4)
            p.drawRoundedRect(44 + offset, 90, 16, 34, 4, 4)
            p.end()
            self._frames.append(QPixmap.fromImage(img))
        self.source_desc = "placeholder (8 frames)"


# ─────────────────────────────────────────────────────────────────────────────
#  GreetingDialog — popover shown on character click
# ─────────────────────────────────────────────────────────────────────────────

class GreetingDialog(QDialog):
    """Small native dialog shown when the user clicks the character."""

    def __init__(self, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Lil Agent")
        self.setWindowFlags(Qt.Dialog | Qt.WindowStaysOnTopHint)
        self.setMinimumWidth(300)

        layout = QVBoxLayout(self)
        layout.setSpacing(12)
        layout.setContentsMargins(16, 16, 16, 16)

        title = QLabel("👋  Hey there, I'm your Lil Agent!")
        title.setStyleSheet("font-size: 14px; font-weight: bold;")
        title.setWordWrap(True)
        layout.addWidget(title)

        body = QLabel(
            "I walk across your desktop keeping you company.\n"
            "Close this dialog and I'll keep on walking!"
        )
        body.setWordWrap(True)
        layout.addWidget(body)

        row = QHBoxLayout()
        row.addStretch()
        ok_btn = QPushButton("Got it 👍")
        ok_btn.setDefault(True)
        ok_btn.clicked.connect(self.accept)
        row.addWidget(ok_btn)
        layout.addLayout(row)


# ─────────────────────────────────────────────────────────────────────────────
#  CharacterWindow — the overlay itself
# ─────────────────────────────────────────────────────────────────────────────

class CharacterWindow(QWidget):
    """
    Transparent, borderless, always-on-top overlay window.

    * The window is positioned just above the bottom panel and walks from one
      screen edge to the other, then reverses direction.
    * ``Qt.X11BypassWindowManagerHint`` is used so the window floats above KWin
      and the KDE panel on X11.
    * A per-frame alpha mask (``setMask``) ensures that only the visible
      (opaque) pixels of the character receive mouse events; transparent pixels
      are fully click-through.
    """

    def __init__(self, screen_rect) -> None:
        super().__init__()
        self._screen       = screen_rect
        self._source       = FrameSource()
        self._w, self._h   = self._source.frame_size()
        self._facing_right = True
        self._dialog_open  = False

        print(f"[lil_agent] Source : {self._source.source_desc}")
        print(f"[lil_agent] Size   : {self._w}×{self._h} px")

        self._setup_window()
        self._current_pixmap = QPixmap()
        self._refresh_frame()   # render first frame + set mask

        # Animation timer — advances walk-cycle frames
        self._anim_timer = QTimer(self)
        self._anim_timer.timeout.connect(self._on_anim_tick)
        self._anim_timer.start(1000 // ANIMATION_FPS)

        # Walk timer — moves the window position across the screen (~60 Hz)
        self._walk_timer = QTimer(self)
        self._walk_timer.timeout.connect(self._on_walk_tick)
        self._walk_timer.start(16)

        self._begin_walk()

    # ── Window setup ──────────────────────────────────────────────────────────

    def _setup_window(self) -> None:
        self.setWindowFlags(
            Qt.FramelessWindowHint
            | Qt.WindowStaysOnTopHint       # _NET_WM_STATE_ABOVE
            | Qt.Tool                       # not in taskbar / Alt-Tab list
            | Qt.X11BypassWindowManagerHint # bypass KWin → above the panel
        )
        self.setAttribute(Qt.WA_TranslucentBackground)
        self.setAttribute(Qt.WA_ShowWithoutActivating)
        self.setFixedSize(self._w, self._h)

    # ── Walk logic ────────────────────────────────────────────────────────────

    def _begin_walk(self) -> None:
        """Place the window at the starting edge and pick a walk direction."""
        self._facing_right = random.choice([True, False])
        y = self._screen.bottom() - PANEL_HEIGHT - self._h
        x = (self._screen.left() - self._w) if self._facing_right \
            else self._screen.right()
        self.move(x, y)

    def _on_walk_tick(self) -> None:
        pos = self.pos()
        if self._facing_right:
            nx = pos.x() + WALK_SPEED
            if nx > self._screen.right() + self._w:
                self._begin_walk()
                return
        else:
            nx = pos.x() - WALK_SPEED
            if nx < self._screen.left() - self._w * 2:
                self._begin_walk()
                return
        self.move(nx, pos.y())

    # ── Animation ─────────────────────────────────────────────────────────────

    def _on_anim_tick(self) -> None:
        self._source.advance()
        self._refresh_frame()

    def _refresh_frame(self) -> None:
        """Fetch the current frame, mirror it if needed, update mask + repaint."""
        px = self._source.current()
        if px.isNull():
            return

        # Mirror horizontally when walking right (source frames face left)
        if self._facing_right:
            px = QPixmap.fromImage(px.toImage().mirrored(True, False))

        # Build a 1-bit mask from the alpha channel so that transparent pixels
        # are click-through and only the visible character body is clickable.
        alpha_mask = QBitmap.fromImage(
            px.toImage()
              .convertToFormat(QImage.Format_ARGB32)
              .createAlphaMask()
        )
        self.setMask(alpha_mask)

        self._current_pixmap = px
        self.update()

    # ── Painting ──────────────────────────────────────────────────────────────

    def paintEvent(self, _event) -> None:
        if self._current_pixmap.isNull():
            return
        p = QPainter(self)
        p.setRenderHint(QPainter.SmoothPixmapTransform)
        p.drawPixmap(0, 0, self._current_pixmap)
        p.end()

    # ── Click handling ────────────────────────────────────────────────────────

    def mousePressEvent(self, event) -> None:
        if event.button() == Qt.LeftButton and not self._dialog_open:
            self._dialog_open = True
            self._walk_timer.stop()
            GreetingDialog(self).exec_()
            self._dialog_open = False
            self._walk_timer.start(16)


# ─────────────────────────────────────────────────────────────────────────────
#  Entry point
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    app = QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)

    screen_rect = app.primaryScreen().geometry()
    window = CharacterWindow(screen_rect)
    window.show()

    print("[lil_agent] Running — click the character to say hi.")
    print("[lil_agent] Press Ctrl+C in this terminal to quit.")
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
